### ISSUE TITLE
$('.channel-actions') doesn't exist anymore

### ISSUE THREAD

**Issue by Deuteu** [romaincointepas/twitch-mini-player#5]
I think you could change it by $('.cn-metabar__more')

**Comment by Deuteu** [comment]
Proposition of changes in #6

**Comment by Deuteu** [comment]
@Smudded or @romaincointepas Would have been great to have some feedback on that from you, just a comment to say you are working on it.

**Comment by Smudded** [comment]
@Deuteu Sorry for the lack of communication there. I'll try to pay more attention to the issues and PRs that get posted.
